name: flutter_customer_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.0+5

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.1
  provider: ^5.0.0
  google_fonts: ^2.1.1
  sqflite: ^2.0.2+1
  sqflite_common_ffi: ^2.1.0+2
  jiffy: ^5.0.0
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.6
  flutterfire_cli: ^0.1.1+2
  syncfusion_flutter_pdfviewer: ^19.4.50-beta
  flutter_local_notifications:
  logging: ^1.0.2
  package_info_plus: ^1.4.0
  store_redirect: ^2.0.1
  responsive_framework: ^0.1.7
  get: ^4.6.1
  get_storage: ^2.0.3
  avinya_flutter:
    path: ../avinya_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/